# -*- mode: ruby -*-
# vi: set ft=ruby :

box_name       =  ENV['UPLF_VAGRANT_BOX_NAME']       || "uplift-local/win-2016-datacenter-soe" 
linked_clone   =  !ENV['UPLF_VAGRANT_LINKED_CLONE'].nil?

vm_name_client  = "client"

# testing strategy:
# dc - apply standard SOE, create domain controller
# client - apply standard SOE, perform domain join

require_relative './../Vagrantfile.rb'

uplift = VagrantPlugins::Uplift::Config()
uplift.set_network_range("192.168.10")

Vagrant.configure("2") do |config|
  
  config.vm.define(vm_name_client) do | vm_config |   
    
    vm_config.vm.box = box_name
    vm_config.vm.box_check_update = false

    uplift.uplift_synced_folder(vm_name_client, vm_config)
    uplift.uplift_1Gb(vm_name_client, vm_config)
    uplift.uplift_hostname(vm_name_client, vm_config, vm_name_client)    
    
    # network, base provision + dc join
    uplift.uplift_client_network(vm_name_client, vm_config, vm_name_client)
    uplift.uplift_win16_dsc_base(vm_name_client, vm_config)
    uplift.uplift_dc_join(vm_name_client, vm_config)
    
    uplift.uplift_win16_dsc_shortcuts(vm_name_client, vm_config)

    vm_config.vm.provision "shell", name: "hostname check", inline: "hostname"

    vm_config.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.linked_clone = linked_clone
    end

  end  

end