# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2.3"

box_name       =  ENV['UPLF_VAGRANT_BOX_NAME'] || "uplift-local/win-2016-datacenter-soe-latest-master" 
linked_clone   =  ENV['UPLF_VAGRANT_LINKED_CLONE'].to_s.empty? == false
machine_folder =  ENV['UPLF_VBMANAGE_MACHINEFOLDER'] || nil

vm_client  = "soe-lts-cl"

# uplift helper for vagrant configurations
uplift = VagrantPlugins::Uplift::Config()

# base uplif configuration
uplift.set_network_range("192.168.10")
uplift.set_config_path("~/.uplift-packer-tests")
uplift.set_vbmanage_machinefolder('all vms', '', machine_folder)

Vagrant.configure("2") do |config|
  
  # additional plugins to be used with this vagrant config
  config.vagrant.plugins = [
    "vagrant-reload",
    "vagrant-uplift"
  ]

  config.vm.define(vm_client) do | vm_config |   
    
    # box config
    vm_config.vm.box = box_name
    vm_config.vm.box_check_update = false

    # uplift - base config
    uplift.set_default_synced_folder(vm_client, vm_config)
    uplift.set_2Gb(vm_client, vm_config)
    uplift.set_hostname(vm_client, vm_config, vm_client)    
    
    # uplift - network, base provision + dc join
    uplift.set_client_network(vm_client, vm_config, vm_client)
    uplift.provision_win16_dsc_soe(vm_client, vm_config)
    uplift.provision_dc_join(vm_client, vm_config)
    
    # uplift - additional helpers
    uplift.provision_win16_dsc_shortcuts(vm_client, vm_config)

    # general check
    vm_config.vm.provision "shell", name: "hostname check", inline: "hostname"

    # virtualbox tuning
    vm_config.vm.provider "virtualbox" do |v|
      v.gui  = false
      
      v.cpus   = uplift.get_vm_cpus(vm_client, 4)
      v.memory = uplift.get_vm_memory(vm_client, 2 * 1024)

      v.customize ['modifyvm', :id, '--cpuexecutioncap', '100'] 
      v.customize ["modifyvm", :id, "--ioapic", "on"]

      v.linked_clone = linked_clone
    end

  end  

end