# -*- mode: ruby -*-
# vi: set ft=ruby :

box_name       =  ENV['UPLF_VAGRANT_BOX_NAME']       || "uplift-local/win-2016-datacenter-vs17" 
linked_clone   =  ENV['UPLF_VAGRANT_LINKED_CLONE'].to_s.empty? == false
machine_folder =  ENV['UPLF_VBMANAGE_MACHINEFOLDER'] || nil

vm_name_client = "vs17-single"

require_relative './../Vagrantfile.rb'

uplift = VagrantPlugins::Uplift::Config()
uplift.set_network_range("192.168.10")

Vagrant.configure("2") do |config|
  
  config.vm.define(vm_name_client) do | vm_config |   
    
    vm_config.vm.box = box_name
    vm_config.vm.box_check_update = false

    uplift.set_default_synced_folder(vm_name_client, vm_config)
    uplift.set_4Gb(vm_name_client, vm_config)
    uplift.set_hostname(vm_name_client, vm_config, vm_name_client)    
    
    # client
    uplift.set_client_network(vm_name_client, vm_config, vm_name_client)
    uplift.provision_win16_dsc_soe(vm_name_client, vm_config)
    uplift.provision_dc_join(vm_name_client, vm_config)

    # shortcuts
    uplift.provision_win16_dsc_shortcuts(vm_name_client, vm_config)

    # vs17 should be already here
    vm_config.vm.provision "shell", name: "hostname check", inline: "hostname"
    vm_config.vm.provision "shell", name: "vs17 testing check", path: "vagrant-test-scripts/vs17-validation.ps1"

    vm_config.vm.provider "virtualbox" do |v|
      v.linked_clone = linked_clone
    end

  end  

end