# -*- mode: ruby -*-
# vi: set ft=ruby :

box_name       =  ENV['UPLF_VAGRANT_BOX_NAME']       || "uplift-local/win-2016-datacenter-sql16" 
linked_clone   =  !ENV['UPLF_VAGRANT_LINKED_CLONE'].nil?

vm_name_sql = "s16-single"

# testing strategy:
# dc - apply standard SOE, create domain controller
# sql - apply standard SOE, perform domain join, ccomplete SQL image

require_relative './../Vagrantfile.rb'

uplift = VagrantPlugins::Uplift::Config()
uplift.set_network_range("192.168.10")

Vagrant.configure("2") do |config|
  
  config.vm.define(vm_name_sql) do | vm_config |   
    
    vm_config.vm.box = box_name
    vm_config.vm.box_check_update = false

    uplift.uplift_synced_folder(vm_name_sql, vm_config)
    uplift.uplift_6Gb(vm_name_sql, vm_config)
    uplift.uplift_hostname(vm_name_sql, vm_config, vm_name_sql)    
    
    # client 
    uplift.uplift_client_network(vm_name_sql, vm_config, vm_name_sql)
    uplift.uplift_win16_dsc_base(vm_name_sql, vm_config)
    uplift.uplift_dc_join(vm_name_sql, vm_config)

    # complete sql image
    uplift.uplift_sql(vm_name_sql, vm_config)

    vm_config.vm.provision "shell", name: "hostname check", inline: "hostname"

    # TODO, add tests to perform CRUD over sql tables
    # just to test SQL server creation and access

    vm_config.vm.provider "virtualbox" do |v|
      v.linked_clone = linked_clone
    end

  end  

end