# -*- mode: ruby -*-
# vi: set ft=ruby :

box_name       =  ENV['UPLF_VAGRANT_BOX_NAME']       || "uplift-local/win-2016-datacenter-sql16" 
linked_clone   =  !ENV['UPLF_VAGRANT_LINKED_CLONE'].nil?
machine_folder =  ENV['UPLF_VBMANAGE_MACHINEFOLDER'] || nil

vm_name_sql = "s16-single"

uplift = VagrantPlugins::Uplift::Config()

# base uplif configuration
uplift.set_network_range("192.168.10")
uplift.set_config_path("~/.uplift-packer-tests")
uplift.set_vbmanage_machinefolder('all vms', '', machine_folder)

Vagrant.configure("2") do |config|
  
  config.vm.define(vm_name_sql) do | vm_config |   
    
    vm_config.vm.box = box_name
    vm_config.vm.box_check_update = false

    uplift.set_default_synced_folder(vm_name_sql, vm_config)
    uplift.set_6Gb(vm_name_sql, vm_config)
    uplift.set_hostname(vm_name_sql, vm_config, vm_name_sql)    
    
    # client 
    uplift.set_client_network(vm_name_sql, vm_config, vm_name_sql)
    uplift.provision_win16_dsc_soe(vm_name_sql, vm_config)
    uplift.provision_dc_join(vm_name_sql, vm_config)

    # complete sql image
    uplift.provision_sql16_complete_image(vm_name_sql, vm_config)

    vm_config.vm.provision "shell", name: "hostname check", inline: "hostname"

    # TODO, add tests to perform CRUD over sql tables
    # just to test SQL server creation and access

    vm_config.vm.provider "virtualbox" do |v|
      v.linked_clone = linked_clone
    end

  end  

end